#pragma once

#define BMT_RELAY_ID 0x01

#define BMT_CID_ESP 0x02E5

#define BMT_RELAY_TX_POWER            ESP_PWR_LVL_P9
#define BMT_RELAY_DEFAULT_TTL         7
#define BMT_RELAY_NET_TRANSMIT_COUNT  7
#define BMT_RELAY_NET_TRANSMIT_INT_MS 10

#define BMT_MONITOR_INTERVAL_MS 30000
